In [ ]:
# Import Section
import csv
import codecs
import sys
import io
import numpy as np
import re
import nltk
# Import Section
import csv, codecs, sys, io, re, random, string
import nltk
nltk.download('stopwords')
nltk.download('punkt')
nltk.download('wordnet')
import pandas as pd
import numpy as np
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import TweetTokenizer
tweet_tokenizer = TweetTokenizer(preserve_case=True, strip_handles=True, reduce_len=True)

# For Classifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.model_selection import cross_val_score
from sklearn import model_selection

# Python script for confusion matrix creation. 
from sklearn.metrics import *

#Global Initialization Section
from ekphrasis.classes.segmenter import Segmenter
seg = Segmenter(corpus="twitter")
import pandas as pd
import numpy as np
import re
import os
import matplotlib as plt
from bs4 import BeautifulSoup
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd
import seaborn as sns
import re,nltk,json, pickle
import tensorflow as tf
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
from bs4 import BeautifulSoup
from tensorflow import keras
from keras.models import Sequential
from tensorflow.keras import regularizers
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.layers import LSTM,GRU,Bidirectional
from tensorflow.keras.models import load_model
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report 
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score,roc_auc_score
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.preprocessing.text import Tokenizer
import pandas as pd
import numpy as np
import re
from re import sub
import multiprocessing
import os
from time import time 
import tensorflow as tf
import keras
from keras.models import Sequential
from keras.layers import LSTM,Dense,Dropout,Activation,Embedding,Flatten,Bidirectional,MaxPooling1D, Conv1D, MaxPooling1D
from keras import regularizers
from keras.preprocessing.text import Tokenizer
##from keras.preprocessing.sequence import pad_sequences
from keras.utils.np_utils import to_categorical
import h5py
import csv
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import nltk
from nltk.corpus import stopwords
import pandas as pd
import numpy as np
import re
import nltk
from nltk.corpus import stopwords
import matplotlib.pyplot as plt
from keras.layers.convolutional import Conv1D 
from numpy import array
from keras.preprocessing.text import one_hot
##from keras.preprocessing.sequence import pad_sequences
from keras_preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers.core import Activation, Dropout, Dense
from keras.layers import Flatten
from keras.layers import GlobalMaxPooling1D
from tensorflow.keras.layers import Embedding
from sklearn.model_selection import train_test_split
from keras.preprocessing.text import Tokenizer
!pip install ekphrasis

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


Reading twitter - 1grams ...
Reading twitter - 2grams ...


/usr/local/lib/python3.7/dist-packages/ekphrasis/classes/exmanager.py:14: FutureWarning: Possible nested set at position 42
  regexes = {k.lower(): re.compile(self.expressions[k]) for k, v in


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!pip install matplotlib-venn

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# For HashtagSegmentation
!pip install ekphrasis
from ekphrasis.classes.segmenter import Segmenter

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# For Classifier
from sklearn.pipeline import Pipeline
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.multiclass import OneVsRestClassifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import LinearSVC
from sklearn.svm import SVC
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier
from sklearn.tree import DecisionTreeClassifier
import nltk
nltk.download('omw-1.4')

[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


True

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
# Python script for confusion matrix creation. 
from sklearn.metrics import *

#Global Initialization Section
seg = Segmenter(corpus="twitter")


def hashtagSegmentation(text):
  givenText=text
  getHashTagFromText = [t for t in givenText.split() if t.startswith('#')]
  segment_the_Hash =''
  getHashtagSegmentedText = givenText
  if getHashTagFromText:
      for eachHashTag in getHashTagFromText:
           eachHashTag=eachHashTag[1:]
           segment_the_Hash = seg.segment(eachHashTag)
           getHashtagSegmentedText = getHashtagSegmentedText+" "+ segment_the_Hash

  return getHashtagSegmentedText


def preprocess_tweet_text(tweet):
    #Remove stopwords
    stop_words = set(stopwords.words('english'))
    #Tokenizer
    tweet_tokens = tweet_tokenizer.tokenize(tweet)
    #tweet_tokens = tweet.split()
    filtered_words = [w for w in tweet_tokens if not w in stop_words]
    from nltk.stem.snowball import SnowballStemmer 
    #the stemmer requires a language parameter 
    ss= SnowballStemmer(language='english')
    stemmed_words = [ss.stem(w) for w in filtered_words]
    lemmatizer = WordNetLemmatizer()
    lemma_words = [lemmatizer.lemmatize(w, pos='a') for w in stemmed_words]
    
    return " ".join(lemma_words)

def preProcessingModule(text):
  returnPreProcessedText=""  
  getHashtagSegmentedText = hashtagSegmentation(text)
  lexicallyNormalizedText = preprocess_tweet_text(getHashtagSegmentedText)


  returnPreProcessedText = getHashtagSegmentedText


  return returnPreProcessedText



Reading twitter - 1grams ...
Reading twitter - 2grams ...


In [ ]:
tweets = []
label = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Training.txt', 'r') as f:
  next(f) # skip headings
  reader=csv.reader(f, dialect="excel-tab")
  for line in reader:
    #print(line[2])
    preProcessedTweetText= preProcessingModule(line[2])
    #print(preProcessedTweetText)
    tweets.append(preProcessedTweetText)
    if(line[1]=="1"):
      label.append("Fake")
    else:
      label.append("Not Fake")
  #print(label)

X_train = np.array(tweets)
Y_train = np.array(label)

In [ ]:
########For Decision Tree Classifier:########
dt_classifier = Pipeline([
     ('count_vectorizer', CountVectorizer(ngram_range=(1, 3))),
     ('clf', OneVsRestClassifier(DecisionTreeClassifier(random_state=0)))])
  
  
  ## Train Classifier
dt_classifier.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
  next(f) # skip headings
  reader=csv.reader(f, dialect="excel-tab")
  for line in reader:
    #print(line[2])
    preProcessedTweetText= preProcessingModule(line[2])
    #print(preProcessedTweetText)
    testTweets.append(preProcessedTweetText)
    if(line[1]=="1"):
      testLabelGold.append("Fake")
    else:
      testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = dt_classifier.predict(X_test)
#print(testLabelPredicted)

# Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 


Confusion Matrix :
[[63 37]
 [39 61]]
Recall Score : 0.62
Precision Score : 0.6200480192076832
Micro Avg. F1 Score : 0.62
Macro Avg. F1 Score : 0.61996199619962
Micro Avg. F1 Score : 0.62
Weighted Avg. F1 Score : 0.61996199619962
Accuracy : 0.62
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.62      0.63      0.62       100
    Not Fake       0.62      0.61      0.62       100

    accuracy                           0.62       200
   macro avg       0.62      0.62      0.62       200
weighted avg       0.62      0.62      0.62       200



In [ ]:

########For SGD Classifier:########
sgd_classifier = Pipeline([
     ('count_vectorizer', CountVectorizer(ngram_range=(1, 3))),
      ('tfidf', TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True, sublinear_tf=False)),
     ('clf', OneVsRestClassifier(MultinomialNB()))])

  
  ## Train Classifier
sgd_classifier.fit(X_train, Y_train)
  
  
## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
  next(f) # skip headings
  reader=csv.reader(f, dialect="excel-tab")
  for line in reader:
    #print(line[2])
    preProcessedTweetText= preProcessingModule(line[2])
    #print(preProcessedTweetText)
    testTweets.append(preProcessedTweetText)
    if(line[1]=="1"):
      testLabelGold.append("Fake")
    else:
      testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = sgd_classifier.predict(X_test)
#print(testLabelPredicted)

# Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 

Confusion Matrix :
[[81 19]
 [54 46]]
Recall Score : 0.635
Precision Score : 0.6538461538461539
Micro Avg. F1 Score : 0.635
Macro Avg. F1 Score : 0.6234687298517085
Micro Avg. F1 Score : 0.635
Weighted Avg. F1 Score : 0.6234687298517084
Accuracy : 0.635
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.60      0.81      0.69       100
    Not Fake       0.71      0.46      0.56       100

    accuracy                           0.64       200
   macro avg       0.65      0.64      0.62       200
weighted avg       0.65      0.64      0.62       200



In [ ]:
from sklearn.ensemble import RandomForestClassifier
########For Random Forest Classifier:########
rfc_classifier = Pipeline([
     ('count_vectorizer', CountVectorizer(ngram_range=(1, 3))),
     ('clf', OneVsRestClassifier(RandomForestClassifier(max_depth=2, random_state=0)))])
  
  ## Train Classifier
rfc_classifier.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
  next(f) # skip headings
  reader=csv.reader(f, dialect="excel-tab")
  for line in reader:
    #print(line[2])
    preProcessedTweetText= preProcessingModule(line[2])
    #print(preProcessedTweetText)
    testTweets.append(preProcessedTweetText)
    if(line[1]=="1"):
      testLabelGold.append("Fake")
    else:
      testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = rfc_classifier.predict(X_test)
#print(testLabelPredicted)

# Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 



Confusion Matrix :
[[79 21]
 [42 58]]
Recall Score : 0.685
Precision Score : 0.6935348885866723
Micro Avg. F1 Score : 0.685
Macro Avg. F1 Score : 0.6814884097171314
Micro Avg. F1 Score : 0.685
Weighted Avg. F1 Score : 0.6814884097171313
Accuracy : 0.685
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.65      0.79      0.71       100
    Not Fake       0.73      0.58      0.65       100

    accuracy                           0.69       200
   macro avg       0.69      0.69      0.68       200
weighted avg       0.69      0.69      0.68       200



In [ ]:
 
########For Multinomial Naive Bayes:########
mnb_classifier = Pipeline([
     ('count_vectorizer', CountVectorizer(ngram_range=(1, 3))),
      ('tfidf', TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True, sublinear_tf=False)),
     ('clf', OneVsRestClassifier(MultinomialNB()))])
  

  
  ## Train Classifier
mnb_classifier.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
  next(f) # skip headings
  reader=csv.reader(f, dialect="excel-tab")
  for line in reader:
    #print(line[2])
    preProcessedTweetText= preProcessingModule(line[2])
    #print(preProcessedTweetText)
    testTweets.append(preProcessedTweetText)
    if(line[1]=="1"):
      testLabelGold.append("Fake")
    else:
      testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = mnb_classifier.predict(X_test)
#print(testLabelPredicted)

# Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 

print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted))

Confusion Matrix :
[[81 19]
 [54 46]]
Recall Score : 0.635
Precision Score : 0.6538461538461539
Micro Avg. F1 Score : 0.635
Macro Avg. F1 Score : 0.6234687298517085
Micro Avg. F1 Score : 0.635
Weighted Avg. F1 Score : 0.6234687298517084
Accuracy : 0.635
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.60      0.81      0.69       100
    Not Fake       0.71      0.46      0.56       100

    accuracy                           0.64       200
   macro avg       0.65      0.64      0.62       200
weighted avg       0.65      0.64      0.62       200



In [ ]:
##for linear SVC
lsvc_classifier = Pipeline([
     ('count_vectorizer', CountVectorizer(ngram_range=(1, 3))),
     ('tfidf', TfidfTransformer(norm='l2', use_idf=True, smooth_idf=True, sublinear_tf=False)),
     ('clf', OneVsRestClassifier(LinearSVC(C=10.0, class_weight=None, dual=True, fit_intercept=True,
      intercept_scaling=1, loss='squared_hinge', max_iter=1000,
      multi_class='ovr', penalty='l2', random_state=0, tol=0.0001,
      verbose=0)))])

  ## Train Classifier
lsvc_classifier.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
    next(f) # skip headings
    reader=csv.reader(f, dialect="excel-tab")
    for line in reader:
          #print(line[2])
        preProcessedTweetText= preProcessingModule(line[2])
          #print(preProcessedTweetText)
        testTweets.append(preProcessedTweetText)
        if(line[1]=="1"):
          testLabelGold.append("Fake")
        else:
          testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = lsvc_classifier.predict(X_test)
  #print(testLabelPredicted)

  # Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 


Confusion Matrix :
[[82 18]
 [47 53]]
Recall Score : 0.675
Precision Score : 0.6910688939840595
Micro Avg. F1 Score : 0.675
Macro Avg. F1 Score : 0.6680201230879235
Micro Avg. F1 Score : 0.675
Weighted Avg. F1 Score : 0.6680201230879236
Accuracy : 0.675
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.64      0.82      0.72       100
    Not Fake       0.75      0.53      0.62       100

    accuracy                           0.68       200
   macro avg       0.69      0.68      0.67       200
weighted avg       0.69      0.68      0.67       200



In [ ]:
from sklearn.neural_network import MLPClassifier

In [ ]:
########For Multilayer Perceptron Classifier:########
mlp_classifier = Pipeline([
     ('count_vectorizer', CountVectorizer(ngram_range=(1, 3))),
     ('clf', OneVsRestClassifier(MLPClassifier(hidden_layer_sizes=(200,), random_state=1, max_iter=60, warm_start=True)))])
  
  ## Train Classifier
mlp_classifier.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
    next(f) # skip headings
    reader=csv.reader(f, dialect="excel-tab")
    for line in reader:
          #print(line[2])
        preProcessedTweetText= preProcessingModule(line[2])
          #print(preProcessedTweetText)
        testTweets.append(preProcessedTweetText)
        if(line[1]=="1"):
          testLabelGold.append("Fake")
        else:
          testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = lsvc_classifier.predict(X_test)
  #print(testLabelPredicted)

  # Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted))

Confusion Matrix :
[[82 18]
 [47 53]]
Recall Score : 0.675
Precision Score : 0.6910688939840595
Micro Avg. F1 Score : 0.675
Macro Avg. F1 Score : 0.6680201230879235
Micro Avg. F1 Score : 0.675
Weighted Avg. F1 Score : 0.6680201230879236
Accuracy : 0.675
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.64      0.82      0.72       100
    Not Fake       0.75      0.53      0.62       100

    accuracy                           0.68       200
   macro avg       0.69      0.68      0.67       200
weighted avg       0.69      0.68      0.67       200



In [ ]:
##valid ensembling with five best classifier without second best MLP
from sklearn.ensemble import VotingClassifier
vtc = VotingClassifier(estimators=[('rfc',rfc_classifier),('dt',dt_classifier) ,('sgd',sgd_classifier),('mnb',mnb_classifier),('lsvc',lsvc_classifier)], 
                       voting='hard',weights=[7,4,4,4,7])
vtc.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
    next(f) # skip headings
    reader=csv.reader(f, dialect="excel-tab")
    for line in reader:
          #print(line[2])
        preProcessedTweetText= preProcessingModule(line[2])
          #print(preProcessedTweetText)
        testTweets.append(preProcessedTweetText)
        if(line[1]=="1"):
          testLabelGold.append("Fake")
        else:
          testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = vtc.predict(X_test)
  #print(testLabelPredicted)

  # Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 


Confusion Matrix :
[[83 17]
 [46 54]]
Recall Score : 0.685
Precision Score : 0.7019871164974343
Micro Avg. F1 Score : 0.685
Macro Avg. F1 Score : 0.6782348885313723
Micro Avg. F1 Score : 0.685
Weighted Avg. F1 Score : 0.6782348885313723
Accuracy : 0.685
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.64      0.83      0.72       100
    Not Fake       0.76      0.54      0.63       100

    accuracy                           0.69       200
   macro avg       0.70      0.69      0.68       200
weighted avg       0.70      0.69      0.68       200



In [ ]:
##valid ensembling with five best classifier with second best MLP
from sklearn.ensemble import VotingClassifier
vtc = VotingClassifier(estimators=[('rfc',rfc_classifier),('mlp',mlp_classifier) ,('sgd',sgd_classifier),('mnb',mnb_classifier),('lsvc',lsvc_classifier)], 
                       voting='hard',weights=[7,7,4,4,7])
vtc.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
    next(f) # skip headings
    reader=csv.reader(f, dialect="excel-tab")
    for line in reader:
          #print(line[2])
        preProcessedTweetText= preProcessingModule(line[2])
          #print(preProcessedTweetText)
        testTweets.append(preProcessedTweetText)
        if(line[1]=="1"):
          testLabelGold.append("Fake")
        else:
          testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = vtc.predict(X_test)
  #print(testLabelPredicted)

  # Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 


Confusion Matrix :
[[87 13]
 [56 44]]
Recall Score : 0.655
Precision Score : 0.690160716476506
Micro Avg. F1 Score : 0.655
Macro Avg. F1 Score : 0.6382794684280884
Micro Avg. F1 Score : 0.655
Weighted Avg. F1 Score : 0.6382794684280885
Accuracy : 0.655
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.61      0.87      0.72       100
    Not Fake       0.77      0.44      0.56       100

    accuracy                           0.66       200
   macro avg       0.69      0.66      0.64       200
weighted avg       0.69      0.66      0.64       200



In [ ]:
## Best three with MLP
from sklearn.ensemble import VotingClassifier
vtc = VotingClassifier(estimators=[('rfc',rfc_classifier),('mlp',mlp_classifier),('lsvc',lsvc_classifier)], 
                       voting='hard',weights=[7,3,7])
vtc.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
    next(f) # skip headings
    reader=csv.reader(f, dialect="excel-tab")
    for line in reader:
          #print(line[2])
        preProcessedTweetText= preProcessingModule(line[2])
          #print(preProcessedTweetText)
        testTweets.append(preProcessedTweetText)
        if(line[1]=="1"):
          testLabelGold.append("Fake")
        else:
          testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = vtc.predict(X_test)
  #print(testLabelPredicted)

  # Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 


Confusion Matrix :
[[87 13]
 [57 43]]
Recall Score : 0.65
Precision Score : 0.6860119047619048
Micro Avg. F1 Score : 0.65
Macro Avg. F1 Score : 0.6321984026902059
Micro Avg. F1 Score : 0.65
Weighted Avg. F1 Score : 0.6321984026902059
Accuracy : 0.65
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.60      0.87      0.71       100
    Not Fake       0.77      0.43      0.55       100

    accuracy                           0.65       200
   macro avg       0.69      0.65      0.63       200
weighted avg       0.69      0.65      0.63       200



In [ ]:
from sklearn.ensemble import VotingClassifier
vtc = VotingClassifier(estimators=[('rfc',rfc_classifier),('mnb',mnb_classifier),('lsvc',lsvc_classifier)], 
                       voting='hard',weights=[7,3,7])
vtc.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
    next(f) # skip headings
    reader=csv.reader(f, dialect="excel-tab")
    for line in reader:
          #print(line[2])
        preProcessedTweetText= preProcessingModule(line[2])
          #print(preProcessedTweetText)
        testTweets.append(preProcessedTweetText)
        if(line[1]=="1"):
          testLabelGold.append("Fake")
        else:
          testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = vtc.predict(X_test)
  #print(testLabelPredicted)

  # Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 


Confusion Matrix :
[[83 17]
 [46 54]]
Recall Score : 0.685
Precision Score : 0.7019871164974343
Micro Avg. F1 Score : 0.685
Macro Avg. F1 Score : 0.6782348885313723
Micro Avg. F1 Score : 0.685
Weighted Avg. F1 Score : 0.6782348885313723
Accuracy : 0.685
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.64      0.83      0.72       100
    Not Fake       0.76      0.54      0.63       100

    accuracy                           0.69       200
   macro avg       0.70      0.69      0.68       200
weighted avg       0.70      0.69      0.68       200



In [ ]:
from sklearn.ensemble import VotingClassifier
vtc = VotingClassifier(estimators=[('rfc',rfc_classifier),('sgd',sgd_classifier),('lsvc',lsvc_classifier)], 
                       voting='hard',weights=[5,3,5])
vtc.fit(X_train, Y_train)
  
  
  ## Test Set Prediction Module
testTweets = []
testLabelGold = []
csv.field_size_limit(500 * 1024 * 1024)  
with open('/content/drive/MyDrive/Dataset/Final_Testing.txt', 'r') as f:
    next(f) # skip headings
    reader=csv.reader(f, dialect="excel-tab")
    for line in reader:
          #print(line[2])
        preProcessedTweetText= preProcessingModule(line[2])
          #print(preProcessedTweetText)
        testTweets.append(preProcessedTweetText)
        if(line[1]=="1"):
          testLabelGold.append("Fake")
        else:
          testLabelGold.append("Not Fake")
  
X_test = np.array(testTweets)
testLabelPredicted = vtc.predict(X_test)
  #print(testLabelPredicted)

  # Evaluation
results = confusion_matrix(testLabelGold, testLabelPredicted) 
    
print ('Confusion Matrix :')
print (results) 

print ('Recall Score :',recall_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Precision Score :',precision_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Macro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='macro'))
print ('Micro Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='micro'))
print ('Weighted Avg. F1 Score :',f1_score(testLabelGold, testLabelPredicted, average='weighted'))
  
print ('Accuracy :',accuracy_score(testLabelGold, testLabelPredicted)) 
  
  
print ('Evaluation Report : ')
print (classification_report(testLabelGold, testLabelPredicted)) 


Confusion Matrix :
[[83 17]
 [46 54]]
Recall Score : 0.685
Precision Score : 0.7019871164974343
Micro Avg. F1 Score : 0.685
Macro Avg. F1 Score : 0.6782348885313723
Micro Avg. F1 Score : 0.685
Weighted Avg. F1 Score : 0.6782348885313723
Accuracy : 0.685
Evaluation Report : 
              precision    recall  f1-score   support

        Fake       0.64      0.83      0.72       100
    Not Fake       0.76      0.54      0.63       100

    accuracy                           0.69       200
   macro avg       0.70      0.69      0.68       200
weighted avg       0.70      0.69      0.68       200

